% results = run_metabolic_demand_12D( ...
%     'noise_on', false, ...
%     'Mvals', 2e-6:0.5e-6:18e-6, ...
%     'tf_seg', 2e4, ...
%     'dt', 0.05);
% 
% figure;
% plot(results.Mvals, results.avgPO2blood, 'k', 'LineWidth', 3);
% xlabel('$M$', 'Interpreter', 'latex');
% ylabel('$P_\mathrm{a}\mathrm{O}_2$', 'Interpreter', 'latex');
% title('12D Closed-Loop');
% grid on;

results = run_fig8_12D_closedloop( ...
    'noise_on', true, ...
    'nRuns', 10, ...
    'Mvals', 2e-6:0.5e-6:18e-6, ...
    'tf_seg', 6e4, ...
    'dt', 0.05);