results = run_metabolic_demand_12D( ...
    'noise_on', true, ...
    'nRuns', 10, ...
    'use_parallel', true, ...
    'save_results', true, ...
    'save_name', 'final_results.mat', ...
    'checkpoint_name', 'checkpoint_results.mat');